@baseUrl = http://localhost:3333
@id = 1

###
GET {{ baseUrl }}/health

###
GET {{ baseUrl }}/products

### create
POST {{ baseUrl }}/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 50000
}

### show
GET {{ baseUrl }}/products/{{ id }}

### update
PUT {{ baseUrl }}/products/{{ id }}
Content-Type: application/json

{
    "name": "Product 1",
    "price": 25000
}

### delete
DELETE {{ baseUrl }}/products/{{ id }}